name: Modify Patches
run-name: Modify Patches

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v4
      with:
        # Checkout the head of the PR branch to avoid detached HEAD
        ref: ${{ github.head_ref }}
        # We need a full history to push, not a shallow clone
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Change documentation files
      run: python .github/workflows/modify_documentation.py

    - name: Change patch files
      run: python .github/workflows/modify_patches.py

    - name: Commit changes
      run: bash .github/workflows/commit_patches.bash
      env:
        # We pass the PR branch name and repo slug to the script
        PR_BRANCH: ${{ github.head_ref }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default token