name: Modify Patches
run-name: Modify Patches
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
   # branches: [ "main" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check modified patchlist
      run:
        if [[ `git status --porcelain modify_patchlist.yaml` ]]; then
          echo "Modified patchlist detected, proceeding with modifications."
        else
          echo "No modifications in patchlist, skipping further steps."
          exit 0
        fi
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Change files
      run: python .github/workflows/modify_patches.py
    - name: Commit changes
      run: |
        if [[ `git status --porcelain` ]]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git config --global pull.rebase false
            git add .
            git commit -m "automation: Update files"
            git push
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}